import { randomUUID } from "node:crypto"
import { appendFileSync } from "node:fs"
import type { Plugin } from "@opencode-ai/plugin"
import {
  applyPromptPatch,
  applyTextPatch,
  BUILTIN_AGENT_DESCRIPTIONS,
  defaultConfigDir,
  defaultSidecarPath,
  debugLogPath,
  fingerprint,
  generatedVariantDescription,
  hasPromptPatch,
  hasRequestPatch,
  loadSidecar,
  modelCatalogFromProviders,
  resolveModel,
  splitModelRef,
  templateContext,
  validateModel,
  type AgentPatch,
  type Diagnostic,
  type SidecarConfig,
  type TemplateContext,
  type VariantConfig,
  variantName,
} from "./config.js"

type AgentConfig = Record<string, any>
type RuntimeRoute = {
  alias: string
  parent: string
  key: string
  patch: VariantConfig
  model?: string
  variant?: string
}
type PendingRoute = RuntimeRoute & {
  token: string
  parentSessionID: string
  targetAgent: string
  fingerprint: string
  createdAt: number
}

const BUILTIN_AGENTS = new Set(Object.keys(BUILTIN_AGENT_DESCRIPTIONS))
const ROUTE_TTL = 10 * 60 * 1000
const MARKER_PREFIX = "<!-- agent-variants-route:"
const MARKER_SUFFIX = " -->"

function marker(token: string) {
  return `${MARKER_PREFIX}${token}${MARKER_SUFFIX}`
}

function attr(value: string | undefined) {
  return (value ?? "").replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

function routeModel(route: RuntimeRoute) {
  return route.model ?? "inherit"
}

function routeSummary(route: RuntimeRoute) {
  return `${route.alias} selected; native agent=${route.parent}; effective model=${routeModel(route)}; variant=${route.variant ?? "default"}`
}

function debugEnabled() {
  try {
    return loadSidecar(defaultSidecarPath()).debug
  } catch {
    return false
  }
}

function mergeOptions(target: Record<string, unknown> | undefined, source: Record<string, unknown> | undefined) {
  return { ...(target ?? {}), ...(source ?? {}) }
}

function applyPatch(target: AgentConfig, patch: AgentPatch, config: SidecarConfig, base?: AgentConfig, context?: TemplateContext) {
  const next = target
  const model = resolveModel(patch.model, config)
  if (model) next.model = model
  if (patch.variant !== undefined) next.variant = patch.variant
  if (patch.temperature !== undefined) next.temperature = patch.temperature
  if (patch.top_p !== undefined) next.top_p = patch.top_p
  if (patch.options !== undefined) next.options = mergeOptions(next.options, patch.options)
  if (patch.color !== undefined) next.color = patch.color
  if (patch.description !== undefined || patch.description_prepend !== undefined || patch.description_append !== undefined) {
    next.description = applyTextPatch(next.description ?? base?.description, patch, context)
  }
  if (patch.prompt !== undefined || patch.prompt_prepend !== undefined || patch.prompt_append !== undefined) {
    next.prompt = applyPromptPatch(next.prompt ?? base?.prompt, patch, context)
  }
  return next
}

function applyConfigPatch(target: AgentConfig, patch: AgentPatch, config: SidecarConfig, base: AgentConfig | undefined, builtin: boolean, context?: TemplateContext) {
  const safePatch = builtin && patch.prompt === undefined ? { ...patch, prompt_prepend: undefined, prompt_append: undefined } : patch
  return applyPatch(target, safePatch, config, base, context)
}

function virtualPatch(alias: string, description: string, patch: VariantConfig, config: SidecarConfig): AgentConfig {
  const result: AgentConfig = {
    mode: "subagent",
    description,
  }
  const model = resolveModel(patch.model, config)
  if (model) result.model = model
  if (patch.variant !== undefined) result.variant = patch.variant
  if (patch.temperature !== undefined) result.temperature = patch.temperature
  if (patch.top_p !== undefined) result.top_p = patch.top_p
  if (patch.options !== undefined) result.options = patch.options
  if (patch.color !== undefined) result.color = patch.color
  result.prompt = `Virtual alias generated by opencode-agent-variants for ${alias}. Runtime routing should execute the parent agent instead.`
  return result
}

function assembleAgents(cfg: Record<string, any>, sidecar: SidecarConfig) {
  cfg.agent = cfg.agent ?? {}
  const virtualRoutes = new Map<string, RuntimeRoute>()
  const parentPromptPatches = new Map<string, AgentPatch>()
  const parentRequestPatches = new Map<string, AgentPatch>()
  const diagnostics: Diagnostic[] = []
  const catalog = modelCatalogFromProviders(cfg.provider)
  const originalAgents = new Set([...Object.keys(cfg.agent), ...Object.keys(BUILTIN_AGENT_DESCRIPTIONS)])
  const generatedAliases = new Map<string, string>()

  for (const [parent, entry] of Object.entries(sidecar.agents)) {
    const parentConfig = cfg.agent[parent] as AgentConfig | undefined
    if (entry.disable) {
      diagnostics.push({ level: "info", agent: parent, message: `Parent "${parent}" is disabled in sidecar config.` })
      continue
    }
    if (parentConfig?.disable === true) {
      diagnostics.push({ level: "info", agent: parent, message: `Parent "${parent}" is disabled in OpenCode config; variants skipped.` })
      continue
    }

    const enabledVariants = Object.entries(entry.variants).filter(([, variant]) => variant.disable !== true)
    if (enabledVariants.length === 0) continue

    const isBuiltin = BUILTIN_AGENTS.has(parent)
    const base = parentConfig ?? (isBuiltin ? { description: BUILTIN_AGENT_DESCRIPTIONS[parent] } : undefined)
    if (!base && !isBuiltin) {
      diagnostics.push({ level: "warning", agent: parent, message: `Parent agent "${parent}" was not found; variants skipped.` })
      continue
    }

    cfg.agent[parent] = applyConfigPatch({ ...(parentConfig ?? {}) }, entry.parent, sidecar, base, isBuiltin, templateContext(parent, undefined, {}, sidecar))
    if (isBuiltin && hasPromptPatch(entry.parent)) parentPromptPatches.set(parent, entry.parent)
    if (isBuiltin && hasRequestPatch(entry.parent)) parentRequestPatches.set(parent, entry.parent)

    for (const [key, variant] of enabledVariants) {
      const alias = variantName(parent, key, variant)
      const modelIssue = validateModel(variant.model, sidecar, catalog)
      if (modelIssue) {
        diagnostics.push({ level: "warning", agent: parent, variant: key, alias, message: `Variant "${alias}" disabled at runtime: ${modelIssue}` })
        continue
      }
      if (alias === parent) {
        diagnostics.push({ level: "error", agent: parent, variant: key, alias, message: `Variant "${alias}" uses the same name as its parent and was skipped.` })
        continue
      }
      const existing = generatedAliases.get(alias)
      if (existing) {
        diagnostics.push({ level: "error", agent: parent, variant: key, alias, message: `Variant "${alias}" duplicates ${existing} and was skipped.` })
        continue
      }
      if (originalAgents.has(alias)) {
        diagnostics.push({ level: "error", agent: parent, variant: key, alias, message: `Variant "${alias}" conflicts with an existing agent and was skipped.` })
        continue
      }
      generatedAliases.set(alias, `${parent}.${key}`)
      const description = generatedVariantDescription(parent, key, variant, sidecar)
      if (isBuiltin) {
        cfg.agent[alias] = virtualPatch(alias, description, variant, sidecar)
        virtualRoutes.set(alias, {
          alias,
          parent,
          key,
          patch: variant,
          model: resolveModel(variant.model, sidecar),
          variant: variant.variant,
        })
        continue
      }

      const copy = applyPatch({ ...(cfg.agent[parent] ?? {}) }, variant, sidecar, cfg.agent[parent], templateContext(parent, key, variant, sidecar))
      copy.description = description
      delete copy.disable
      cfg.agent[alias] = copy
    }
  }

  return { virtualRoutes, parentPromptPatches, parentRequestPatches, diagnostics }
}

function textFromParts(parts: any[]) {
  const primary = parts.filter((part) => part?.type === "text" && !part.synthetic).map((part) => part.text).join("\n\n")
  if (primary.trim()) return primary
  return parts.filter((part) => part?.type === "text").map((part) => part.text).join("\n\n")
}

function takeMarkerRoute(parts: any[], routes: Map<string, RuntimeRoute>) {
  for (const part of parts) {
    if (part?.type !== "text" || typeof part.text !== "string") continue
    const start = part.text.indexOf(MARKER_PREFIX)
    if (start < 0) continue
    const end = part.text.indexOf(MARKER_SUFFIX, start)
    if (end < 0) continue
    const token = part.text.slice(start + MARKER_PREFIX.length, end)
    const route = routes.get(token)
    part.text = `${part.text.slice(0, start)}${part.text.slice(end + MARKER_SUFFIX.length)}`.trim()
    routes.delete(token)
    if (route) return { token, route }
  }
}

function removePendingToken(list: PendingRoute[], token: string) {
  const index = list.findIndex((item) => item.token === token)
  if (index >= 0) list.splice(index, 1)
}

function cleanupPending(list: PendingRoute[], routes?: Map<string, RuntimeRoute>) {
  const cutoff = Date.now() - ROUTE_TTL
  while (list[0] && list[0].createdAt < cutoff) {
    const item = list.shift()
    if (item) routes?.delete(item.token)
  }
}

function takePending(list: PendingRoute[], input: { parentSessionID?: string; agent?: string; fingerprint: string }) {
  const exact = list.findIndex(
    (item) => item.parentSessionID === input.parentSessionID && item.targetAgent === input.agent && item.fingerprint === input.fingerprint,
  )
  if (exact >= 0) return list.splice(exact, 1)[0]
  const fallback = list.findIndex((item) => item.parentSessionID === input.parentSessionID && item.targetAgent === input.agent)
  if (fallback >= 0) return list.splice(fallback, 1)[0]
}

function getData<T>(value: T | { data?: T } | undefined): T | undefined {
  if (value && typeof value === "object" && "data" in value) return value.data
  return value as T | undefined
}

async function getSession(client: any, sessionID: string) {
  return getData(await client.session.get({ path: { id: sessionID } }).catch(() => undefined)) as { parentID?: string; agent?: string } | undefined
}

async function debugToast(client: any, enabled: boolean, title: string, message: string) {
  if (!enabled && !debugEnabled()) return
  try {
    appendFileSync(debugLogPath(defaultConfigDir()), `${new Date().toISOString()} ${title}: ${message}\n`)
  } catch {
    // Debug logging should never affect routing.
  }
  await client.tui?.showToast?.({
    body: {
      title,
      message,
      variant: "info",
      duration: 12000,
    },
  }).catch(() => undefined)
}

async function warningToast(client: any, diagnostic: Diagnostic) {
  try {
    appendFileSync(debugLogPath(defaultConfigDir()), `${new Date().toISOString()} ${diagnostic.level.toUpperCase()}: ${diagnostic.message}\n`)
  } catch {
    // Diagnostics should never affect startup.
  }
  if (diagnostic.level === "info") return
  await client.tui?.showToast?.({
    body: {
      title: diagnostic.level === "error" ? "Agent variant skipped" : "Agent variant disabled",
      message: diagnostic.message,
      variant: diagnostic.level === "error" ? "error" : "warning",
      duration: 15000,
    },
  }).catch(() => undefined)
}

function applyRequestPatch(output: { temperature?: number; topP?: number; options: Record<string, any> }, patch: AgentPatch) {
  if (patch.temperature !== undefined) output.temperature = patch.temperature
  if (patch.top_p !== undefined) output.topP = patch.top_p
  if (patch.options !== undefined) Object.assign(output.options, patch.options)
}

function applySystemPatch(system: string[], patch: AgentPatch, context?: TemplateContext) {
  if (!hasPromptPatch(patch)) return
  const current = system[0] ?? ""
  system[0] = applyPromptPatch(current, patch, context)
}

function annotateTaskOutput(text: string, route: RuntimeRoute) {
  const annotated = text.replace(
    /^<task\b([^>]*)>/,
    `<task$1 agent_variant="${attr(route.alias)}" routed_agent="${attr(route.parent)}" effective_model="${attr(routeModel(route))}" model_variant="${attr(route.variant ?? "default")}">`,
  )
  if (annotated !== text) return annotated
  return [`<agent_variant alias="${attr(route.alias)}" routed_agent="${attr(route.parent)}" effective_model="${attr(routeModel(route))}" model_variant="${attr(route.variant ?? "default")}" />`, text].join("\n")
}

const plugin: Plugin = async (input) => {
  const sidecar = loadSidecar(defaultSidecarPath())
  let virtualRoutes = new Map<string, RuntimeRoute>()
  let parentPromptPatches = new Map<string, AgentPatch>()
  let parentRequestPatches = new Map<string, AgentPatch>()
  const pending: PendingRoute[] = []
  const tokenRoutes = new Map<string, RuntimeRoute>()
  const bySession = new Map<string, RuntimeRoute>()
  const byCall = new Map<string, RuntimeRoute>()

  return {
    config: async (cfg) => {
      const assembled = assembleAgents(cfg as Record<string, any>, sidecar)
      virtualRoutes = assembled.virtualRoutes
      parentPromptPatches = assembled.parentPromptPatches
      parentRequestPatches = assembled.parentRequestPatches
      for (const diagnostic of assembled.diagnostics) await warningToast(input.client, diagnostic)
    },
    "tool.execute.before": async (hookInput, output) => {
      if (hookInput.tool !== "task") return
      const args = output.args as { subagent_type?: string; prompt?: string; description?: string }
      if (!args?.subagent_type || !args.prompt) return
      const route = virtualRoutes.get(args.subagent_type)
      if (!route) return
      cleanupPending(pending, tokenRoutes)
      const token = randomUUID()
      tokenRoutes.set(token, route)
      byCall.set(hookInput.callID, route)
      pending.push({
        ...route,
        token,
        parentSessionID: hookInput.sessionID,
        targetAgent: route.parent,
        fingerprint: fingerprint({
          parentSessionID: hookInput.sessionID,
          agent: route.parent,
          prompt: args.prompt,
          description: args.description,
        }),
        createdAt: Date.now(),
      })
      args.prompt = `${args.prompt}\n\n${marker(token)}`
      args.subagent_type = route.parent
      await debugToast(
        input.client,
        sidecar.debug,
        "Agent variant routed",
        `${routeSummary(route)}; token=${token.slice(0, 8)}`,
      )
    },
    "tool.execute.after": async (hookInput, output) => {
      if (hookInput.tool !== "task") return
      const route = byCall.get(hookInput.callID)
      if (!route) return
      byCall.delete(hookInput.callID)
      output.title = `${output.title} (@${route.alias} variant)`
      output.metadata = {
        ...output.metadata,
        agentVariant: {
          alias: route.alias,
          routedAgent: route.parent,
          effectiveModel: routeModel(route),
          modelVariant: route.variant ?? "default",
        },
        model: splitModelRef(route.model) ?? output.metadata?.model,
      }
      output.output = annotateTaskOutput(output.output, route)
      await debugToast(input.client, sidecar.debug, "Agent variant result annotated", routeSummary(route))
    },
    "chat.message": async (hookInput, output) => {
      const markerRoute = takeMarkerRoute(output.parts as any[], tokenRoutes)
      if (markerRoute) {
        removePendingToken(pending, markerRoute.token)
        bySession.set(hookInput.sessionID, markerRoute.route)
        const model = splitModelRef(markerRoute.route.model)
        if (model) {
          output.message.model = {
            providerID: model.providerID,
            modelID: model.modelID,
          }
          if (markerRoute.route.variant) (output.message.model as { variant?: string }).variant = markerRoute.route.variant
        } else if (markerRoute.route.variant) {
          (output.message.model as { variant?: string }).variant = markerRoute.route.variant
        }
        await debugToast(
          input.client,
          sidecar.debug,
          "Agent variant model applied",
          `${routeSummary(markerRoute.route)}; session=${hookInput.sessionID}; token=${markerRoute.token.slice(0, 8)}`,
        )
        return
      }
      const session = await getSession(input.client, hookInput.sessionID)
      const fp = fingerprint({
        parentSessionID: session?.parentID ?? "",
        agent: output.message.agent,
        prompt: textFromParts(output.parts as any[]),
      })
      const route = takePending(pending, {
        parentSessionID: session?.parentID,
        agent: output.message.agent,
        fingerprint: fp,
      })
      if (!route) return
      bySession.set(hookInput.sessionID, route)
      const model = splitModelRef(route.model)
      if (model) {
        output.message.model = {
          providerID: model.providerID,
          modelID: model.modelID,
        }
        if (route.variant) (output.message.model as { variant?: string }).variant = route.variant
      } else if (route.variant) {
        (output.message.model as { variant?: string }).variant = route.variant
      }
      await debugToast(
        input.client,
        sidecar.debug,
        "Agent variant model applied (fallback)",
        `${routeSummary(route)}; session=${hookInput.sessionID}`,
      )
    },
    "chat.params": async (hookInput, output) => {
      const routed = bySession.get(hookInput.sessionID)
      const parent = parentRequestPatches.get(hookInput.agent)
      if (parent) applyRequestPatch(output, parent)
      if (routed) applyRequestPatch(output, routed.patch)
    },
    "experimental.chat.system.transform": async (hookInput, output) => {
      if (!hookInput.sessionID) return
      const routed = bySession.get(hookInput.sessionID)
      if (routed) {
        const parent = parentPromptPatches.get(routed.parent)
        if (parent) applySystemPatch(output.system, parent, templateContext(routed.parent, undefined, {}, sidecar))
        applySystemPatch(output.system, routed.patch, templateContext(routed.parent, routed.key, routed.patch, sidecar))
        return
      }
      const session = await getSession(input.client, hookInput.sessionID)
      const parent = session?.agent ? parentPromptPatches.get(session.agent) : undefined
      if (parent && session?.agent) applySystemPatch(output.system, parent, templateContext(session.agent, undefined, {}, sidecar))
    },
  }
}

export default plugin
